name: sat
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  carousel_pro:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/providers/dialogtv.png
   - assets/providers/peotv.png
   - assets/providers/dishtv.png
   - assets/providers/airtel.png
   - assets/providers/sundirect.png
   - assets/providers/tatasky.png
   - assets/providers/videocon.png
   - assets/channels/sports/DDSports.png
   - assets/channels/sports/DiscoverySport.png
   - assets/channels/sports/EuroSport.png
   - assets/channels/sports/OutdoorChannel.png
   - assets/channels/sports/OutdoorChannelHD.png
   - assets/channels/sports/SetantaSports.png
   - assets/channels/sports/SetantaSportsHD.png
   - assets/channels/sports/SonyEspn.png
   - assets/channels/sports/SonyEspnHD.png
   - assets/channels/sports/SonySix.png
   - assets/channels/sports/SonySixHD.png
   - assets/channels/sports/SonyTen1.png
   - assets/channels/sports/SonyTen1HD.png
   - assets/channels/sports/SonyTen2.jpg
   - assets/channels/sports/SonyTen2HD.jpg
   - assets/channels/sports/SonyTen3.png
   - assets/channels/sports/StarSports1.jpg
   - assets/channels/sports/StarSports1Hindi.jpg
   - assets/channels/sports/StarSports1Tamil.jpg
   - assets/channels/sports/StarSports2.jpg
   - assets/channels/sports/StarSports2HD.jpg
   - assets/channels/sports/StarSports3.png
   - assets/channels/sports/StarSportsFirst.jpg
   - assets/channels/sports/StarSportsSelect1.jpg
   - assets/channels/sports/StarSportsSelect1HD.jpg
   - assets/channels/sports/StarSportsSelect2.jpg
   - assets/channels/sports/StarSportsSelect2HD.jpg
   - assets/channels/sports/StarSports1HD.jpg
   - assets/channels/sports/StarSports1HindiHD.jpg
   - assets/channels/sports/TenCricket.png
   - assets/channels/sports/Wow.png
   - assets/channels/sports/WowHD.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
